flags: {}
packages:
- '.'
extra-deps:
- GLURaw-1.5.0.1
- GLUT-2.7.0.2
- ObjectName-1.1.0.0
- OpenGL-2.12.0.1
- OpenGLRaw-2.5.3.0
- gloss-1.9.4.1
- gloss-raster-1.9.4.1
- gloss-rendering-1.9.3.1
resolver: lts-3.5
